[32m2024-10-26 02:01:53 +0800[0m - dagster - [34mDEBUG[0m - ppa_migration_pipeline - eaaab67a-d493-4838-adda-aecb4a945257 - 173132 - LOGS_CAPTURED - Started capturing logs in process (pid: 173132).
[32m2024-10-26 02:01:53 +0800[0m - dagster - [34mDEBUG[0m - ppa_migration_pipeline - eaaab67a-d493-4838-adda-aecb4a945257 - 173132 - transform_asnaf_data - STEP_START - Started execution of step "transform_asnaf_data".
[32m2024-10-26 02:01:53 +0800[0m - dagster - [34mINFO[0m - ppa_migration_pipeline - eaaab67a-d493-4838-adda-aecb4a945257 - transform_asnaf_data - Reading data from PostgreSQL.
[32m2024-10-26 02:01:53 +0800[0m - dagster - [34mERROR[0m - [31mppa_migration_pipeline - eaaab67a-d493-4838-adda-aecb4a945257 - transform_asnaf_data - Error fetching data: column "vwlzs_HealthLevel" does not exist
LINE 88:     "vwlzs_HealthLevel"::int AS "Healthlevel",
             ^
HINT:  Perhaps you meant to reference the column "vwlzs_asnaf.vwlzs_Healthlevel".
[0m
[32m2024-10-26 02:01:53 +0800[0m - dagster - [34mERROR[0m - [31mppa_migration_pipeline - eaaab67a-d493-4838-adda-aecb4a945257 - 173132 - transform_asnaf_data - STEP_FAILURE - Execution of step "transform_asnaf_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "transform_asnaf_data"::

psycopg2.errors.UndefinedColumn: column "vwlzs_HealthLevel" does not exist
LINE 88:     "vwlzs_HealthLevel"::int AS "Healthlevel",
             ^
HINT:  Perhaps you meant to reference the column "vwlzs_asnaf.vwlzs_Healthlevel".


Stack Trace:
  File "/home/mnshuhailey/dev/dev-env/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/mnshuhailey/dev/dev-env/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/mnshuhailey/dev/dev-env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/mnshuhailey/dev/dev-env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnshuhailey/dev/ppa-dagster/ppa_migration/ops/transform_asnaf_data.py", line 21, in transform_asnaf_data
    cursor_pg.execute(fetch_data_query)
[0m
